### ISSUE TITLE
Documentation error in SimpleTriggerImpl UpdateAfterMisfire

### ISSUE THREAD

**Issue by IRQ0x00** [quartznet/quartznet#267]
While exmaning samples from Quartz project, I found example 5 with misfire code. There is a comment:

The other
    /// trigger uses the default "smart policy" misfire instruction, which causes
    /// the trigger to advance to its next fire time (skipping those that it has
    /// missed) - so that it does not refire immediately, but rather at the next
    /// scheduled time.

This can be proved with code in SimpleTriggerImpl.cs:

![quartz2](https://cloud.githubusercontent.com/assets/12661188/7935280/5247bc36-0938-11e5-83d8-9bd84f6f479b.png)
However If I open documentation for "SimpleTriggerImpl UpdateAfterMisfire Method", I see there:

![quartz3](https://cloud.githubusercontent.com/assets/12661188/7935320/b4cec246-0938-11e5-931b-1c828c2e129e.png)

Is this an error? Working example with smart policy enabled (the very first job "statefulJob1" from example 5) follows RescheduleNext rule but not RescheduleNow rule:

![quartz4](https://cloud.githubusercontent.com/assets/12661188/7935394/4fb0d5e2-0939-11e5-90d6-3cfc5cabe4f8.png)

An important note: before running the example I had to change default quartz.jobStore.misfireThreshold setting from default of 60000 to not more than 7000 so that there is a real missfire. Otherwise a 10sec delay in a job will not exceed 1min misfireThreshold.

**Comment by lahma** [comment]
Thanks for reporting, documentation is now fixed in master.

**Comment by IRQ0x00** [comment]
My screenshot is from sourceforge.net (API 2.0 link on quartz web page). It is not fixed, only GitHub project is fixed.

**Comment by lahma** [comment]
Pushed to sourceforge too.
